MAPPING_LANG_TO_KEY = {
    "Amharic": "amh_Ethi",
    "Arabic": "arb_Arab",
    "Assamese": "asm_Beng",
    "Bambara": "bam_Latn",
    "Bashkir": "bak_Cyrl",
    "Basque": "eus_Latn",
    "Belarusian": "bel_Cyrl",
    "Bemba": "bem_Latn",
    "Bengali": "ben_Beng",
    "Bulgarian": "bul_Cyrl",
    "Burmese": "mya_Mymr",
    "Cebuano": "ceb_Latn",
    "Chinese": "zho_Hans",
    "Traditional Chinese": "zho_Hant",
    "Yue Chinese": "yue_Hant",
    "Croatian": "hrv_Latn",
    "Czech": "ces_Latn",
    "Danish": "dan_Latn",
    "Dzongkha": "dzo_Tibt",
    "English": "eng_Latn",
    "Esperanto": "epo_Latn",
    "Estonian": "est_Latn",
    "Ewe": "ewe_Latn",
    "Faroese": "fao_Latn",
    "Fijian": "fij_Latn",
    "Finnish": "fin_Latn",
    "Fon": "fon_Latn",
    "French": "fra_Latn",
    "German": "deu_Latn",
    "Greek": "ell_Grek",
    "Gujarati": "guj_Gujr",
    "Hausa": "hau_Latn",
    "Hebrew": "heb_Hebr",
    "Hindi": "hin_Deva",
    "Hungarian": "hun_Latn",
    "Icelandic": "isl_Latn",
    "Igbo": "ibo_Latn",
    "Indonesian": "ind_Latn",
    "Irish": "gle_Latn",
    "Japanese": "jpn_Jpan",
    "Javanese": "jav_Latn",
    "Kannada": "kan_Knda",
    "Kazakh": "kaz_Cyrl",
    "Khmer": "khm_Khmr",
    "Kinyarwanda": "kin_Latn",
    "Kyrgyz": "kir_Cyrl",
    "Korean": "kor_Hang",
    "Lao": "lao_Laoo",
    "Lingala": "lin_Latn",
    "Lithuanian": "lit_Latn",
    "Ganda": "lug_Latn", # Luganda = Ganda
    "Luganda": "lug_Latn",
    "Luxembourgish": "ltz_Latn",
    "Malagasy": "plt_Latn", # Plateau Malagasy
    "Malayalam": "mal_Mlym",
    "Maori": "mri_Latn",
    "Marathi": "mar_Deva",
    "Meitei": "mni_Beng",
    "Nepali": "npi_Deva",
    "Norwegian": "nob_Latn",
    "Occitan": "oci_Latn",
    "Oromo": "gaz_Latn", # West Central Oromo
    "Portuguese": "por_Latn",
    "Romanian": "ron_Latn",
    "Rundi": "run_Latn",
    "Russian": "rus_Cyrl",
    "Samoan": "smo_Latn",
    "Sanskrit": "san_Deva",
    "Shona": "sna_Latn",
    "Sindhi": "snd_Arab",
    "Sinhala": "sin_Sinh",
    "Somali": "som_Latn",
    "Spanish": "spa_Latn",
    "Sundanese": "sun_Latn",
    "Swahili": "swh_Latn",
    "Swati": "ssw_Latn",
    "Swedish": "swe_Latn",
    "Tajik": "tgk_Cyrl",
    "Tamil": "tam_Taml",
    "Tatar": "tat_Cyrl",
    "Telugu": "tel_Telu",
    "Tigrinya": "tir_Ethi",
    "Tsonga": "tso_Latn",
    "Tumbuka": "tum_Latn",
    "Turkish": "tur_Latn",
    "Turkmen": "tuk_Latn",
    "Tswana": "tsn_Latn",
    "Twi": "twi_Latn",
    "Ukrainian": "ukr_Cyrl",
    "Umbundu": "umb_Latn",
    "Urdu": "urd_Arab",
    "Uyghur": "uig_Arab",
    "Uzbek": "uzn_Latn", # Northern Uzbek
    "Vietnamese": "vie_Latn",
    "Welsh": "cym_Latn",
    "Wolof": "wol_Latn",
    "Xhosa": "xho_Latn",
    "Yoruba": "yor_Latn",
    "Zulu": "zul_Latn",
    "Asturian": "ast_Latn",
    "Bhojpuri": "bho_Deva",
    "Guarani": "grn_Latn",
    "Waray": "war_Latn",
    "N'ko": "nqo_Nkoo",
    "Emakhuwa": "vmw_Latn",
    "Farsi": "pes_Arab",
    "Malay": "zsm_Latn",
    "Tagalog": "tgl_Latn",
}

NON_FLORES = [
    "N'ko", "Emakhuwa"
]

MAPPING_LANG_TO_KEY_NTREX = {
    "Amharic": "amh_Ethi",
    "Azerbaidjani": "aze_Latn",
    "Belarusian": "bel_Cyrl",
    "Bashkir": "bak_Cyrl",
    "Basque": "eus_Latn",
    "Bemba": "bem_Latn",
    "Bengali": "ben_Beng",
    "Bulgarian": "bul_Cyrl",
    "Burmese": "mya_Mymr",
    "Catalan": "cat_Latn",
    "Czech": "ces_Latn",
    "Danish": "dan_Latn",
    "Dhivehi": "div_Thaa",
    "Dzongkha": "dzo_Tibt",
    "English": "eng_Latn",
    "Estonian": "est_Latn",
    "Faroese": "fao_Latn",
    "Ewe": "ewe_Latn",
    "Fijian": "fij_Latn",
    "French": "fra_Latn",
    "Igbo": "ibo_Latn",
    "Irish": "gle_Latn",
    "Faroese": "fao_Latn",
    "Finnish": "fin_Latn",
    "French": "fra_Latn",
    "German": "deu_Latn",
    "Gujarati": "guj_Gujr",
    "Hausa": "hau_Latn",
    "Hindi": "hin_Deva",
    "Japanese": "jpn_Jpan",
    "Kannada": "kan_Knda",
    "Kazakh": "kaz_Cyrl",
    "Khmer": "khm_Khmr",
    "Kinyarwanda": "kin_Latn",
    "Kyrgyz": "kir_Cyrl",
    "Lao": "lao_Laoo",
    "Lithuanian": "lit_Latn",
    "Malagasy": "mlg_Latn",
    "Malay": "msa_Latn",
    "Malayalam": "mal_Mlym",
    "Maori": "mri_Latn",
    "Marathi": "mar_Deva",
    "Nepali": "nep_Deva",
    "Oromo": "orm_Ethi",
    "Portuguese": "por_Latn",
    "Samoan": "smo_Latn",
    "Shona": "sna_Latn",
    "Sinhala": "sin_Sinh",
    "Somali": "som_Latn",
    "Spanish": "spa_Latn",
    "Swahili": "swa_Latn",
    "Swati": "ssw_Latn",
    "Tajik": "tgk_Cyrl",
    "Tamil": "tam_Taml",
    "Telugu": "tel_Telu",
    "Tigrinya": "tir_Ethi",
    "Turkmen": "tuk_Latn",
    "Turkish": "tur_Latn",
    "Tswana": "tsn_Latn",
    "Uyghur": "uig_Arab",
    "Urdu": "urd_Arab",
    "Uzbek": "uzb_Latn",
    "Wolof": "wol_Latn",
    "Xhosa": "xho_Latn",
    "Yoruba": "yor_Latn",
    "Zulu": "zul_Latn"
}

LANGUAGE_PAIRS = (
    "en-ar_EG", "en-ar_SA", "en-bg_BG", "en-bn_IN", "en-ca_ES", "en-cs_CZ", "en-da_DK", "en-de_DE",
    "en-el_GR", "en-es_MX", "en-et_EE", "en-fa_IR", "en-fi_FI", "en-fil_PH", "en-fr_CA", "en-fr_FR",
    "en-gu_IN", "en-he_IL", "en-hi_IN", "en-hr_HR", "en-hu_HU", "en-id_ID", "en-is_IS", "en-it_IT",
    "en-ja_JP", "en-kn_IN", "en-ko_KR", "en-lt_LT", "en-lv_LV", "en-ml_IN", "en-mr_IN", "en-nl_NL",
    "en-no_NO", "en-pa_IN", "en-pl_PL", "en-pt_BR", "en-pt_PT", "en-ro_RO", "en-ru_RU", "en-sk_SK",
    "en-sl_SI", "en-sr_RS", "en-sv_SE", "en-sw_KE", "en-sw_TZ", "en-ta_IN", "en-te_IN", "en-th_TH",
    "en-tr_TR", "en-uk_UA", "en-ur_PK", "en-vi_VN", "en-zh_CN", "en-zh_TW", "en-zu_ZA",
)

LANGUAGE_BY_CODE = {
    "ar_EG": "Arabic",
    "ar_SA": "Arabic",
    "bg_BG": "Bulgarian",
    "bn_BD": "Bengali",
    "bn_IN": "Bengali",
    "ca_ES": "Catalan",
    "cs_CZ": "Czech",
    "da_DK": "Danish",
    "de_DE": "German",
    "el_GR": "Greek",
    "es_MX": "Spanish",
    "et_EE": "Estonian",
    "fa_IR": "Farsi",
    "fi_FI": "Finnish",
    "fil_PH": "Filipino",
    "fr_CA": "French",
    "fr_FR": "French",
    "gu_IN": "Gujarati",
    "he_IL": "Hebrew",
    "hi_IN": "Hindi",
    "hr_HR": "Croatian",
    "hu_HU": "Hungarian",
    "id_ID": "Indonesian",
    "is_IS": "Icelandic",
    "it_IT": "Italian",
    "ja_JP": "Japanese",
    "kn_IN": "Kannada",
    "ko_KR": "Korean",
    "lt_LT": "Lithuanian",
    "lv_LV": "Latvian",
    "ml_IN": "Malayalam",
    "mr_IN": "Marathi",
    "nl_NL": "Dutch",
    "no_NO": "Norwegian",
    "pa_IN": "Punjabi",
    "pl_PL": "Polish",
    "pt_BR": "Portuguese",
    "pt_PT": "Portuguese",
    "ro_RO": "Romanian",
    "ru_RU": "Russian",
    "sk_SK": "Slovak",
    "sl_SI": "Slovenian",
    "sr_RS": "Serbian",
    "sv_SE": "Swedish",
    "sw_KE": "Swahili",
    "sw_TZ": "Swahili",
    "ta_IN": "Tamil",
    "te_IN": "Telugu",
    "th_TH": "Thai",
    "tr_TR": "Turkish",
    "uk_UA": "Ukrainian",
    "ur_PK": "Urdu",
    "vi_VN": "Vietnamese",
    "zh_CN": "Mandarin",
    "zh_TW": "Mandarin",
    "zu_ZA": "Zulu",
}

CODE_BY_LANGUAGE = {v : k for k, v in LANGUAGE_BY_CODE.items()}

REGION_BY_CODE = {
    "ar_EG": "Egypt",
    "ar_SA": "Saudi Arabia",
    "bg_BG": "Bulgaria",
    "bn_BD": "Bangladesh",
    "bn_IN": "India",
    "ca_ES": "Spain",
    "cs_CZ": "Czechia",
    "da_DK": "Denmark",
    "de_DE": "Germany",
    "el_GR": "Greece",
    "es_MX": "Mexico",
    "et_EE": "Estonia",
    "fa_IR": "Iran",
    "fi_FI": "Finland",
    "fil_PH": "Philippines",
    "fr_CA": "Canada",
    "fr_FR": "France",
    "gu_IN": "India",
    "he_IL": "Israel",
    "hi_IN": "India",
    "hr_HR": "Croatia",
    "hu_HU": "Hungary",
    "id_ID": "Indonesia",
    "is_IS": "Iceland",
    "it_IT": "Italy",
    "ja_JP": "Japan",
    "kn_IN": "India",
    "ko_KR": "South Korea",
    "lt_LT": "Lithuania",
    "lv_LV": "Latvia",
    "ml_IN": "India",
    "mr_IN": "India",
    "nl_NL": "Netherlands",
    "no_NO": "Norway",
    "pa_IN": "India",
    "pl_PL": "Poland",
    "pt_BR": "Brazil",
    "pt_PT": "Portugal",
    "ro_RO": "Romania",
    "ru_RU": "Russia",
    "sk_SK": "Slovakia",
    "sl_SI": "Slovenia",
    "sr_RS": "Serbia",
    "sv_SE": "Sweden",
    "sw_KE": "Kenya",
    "sw_TZ": "Tanzania",
    "ta_IN": "India",
    "te_IN": "India",
    "th_TH": "Thailand",
    "tr_TR": "Turkey",
    "uk_UA": "Ukraine",
    "ur_PK": "Pakistan",
    "vi_VN": "Vietnam",
    "zh_CN": "China",
    "zh_TW": "Taiwan",
    "zu_ZA": "South Africa",
}
